// Données partagées entre Réalisations et ProjectDetail
export const projects = [
  {
    id: 99,
    slug: 'projet-en-cours',
    title: 'Projet en cours',
    category: 'Rénovation complète',
    location: 'Cannes',
    surface: 'À venir',
    year: '2026',
    image: '/about-4.jpg',
    tags: ['villa', 'renovation'],
    description: '',
    mission: '',
    budget: '',
    duration: '',
    gallery: [],
    comingSoon: true,
  },
  {
    id: 14,
    slug: 'villa-opio',
    title: 'Villa d\'Opio',
    category: 'Rénovation complète',
    location: 'Opio',
    surface: 'Villa',
    year: '2018',
    image: '/projects/villa-opio/opio-4.jpg',
    tags: ['villa', 'renovation', 'conception'],
    description: 'Rénovation complète d\'une villa provençale à Opio. Du couloir d\'entrée aux fenêtres cintrées en acier jusqu\'au pool-house en pierre et charpente bois, chaque espace a été repensé avec soin : cuisine avec îlot central, séjour avec cheminée ancienne, salle de bain avec vasque en bois fossile. Un projet qui mêle authenticité des matériaux et confort contemporain.',
    mission: 'Rénovation complète & maîtrise d\'œuvre',
    budget: 'Sur demande',
    duration: 'Sur demande',
    gallery: [
      '/projects/villa-opio/opio-4.jpg',
      '/projects/villa-opio/opio-10.jpg',
      '/projects/villa-opio/opio-7.jpg',
      '/projects/villa-opio/opio-2.jpg',
      '/projects/villa-opio/opio-6.jpg',
      '/projects/villa-opio/opio-3.jpg',
      '/projects/villa-opio/opio-1.jpg',
      '/projects/villa-opio/opio-5.jpg',
      '/projects/villa-opio/opio-8.jpg',
      '/projects/villa-opio/opio-9.jpg',
    ],
  },
  {
    id: 7,
    slug: 'villa-roquefort-les-pins',
    title: 'Villa contemporaine — Roquefort-les-Pins',
    category: 'Maîtrise d\'œuvre',
    location: 'Roquefort-les-Pins',
    surface: '300 m²',
    year: '2014',
    image: '/projects/roquefort/roquefort-2.jpg',
    tags: ['villa', 'conception', 'renovation'],
    description: 'Structure imposante avec débord en porte-à-faux, toiture monopente, grandes baies vitrées et terrasse avec piscine. Christine Thémélidis et un architecte DPLG forment un tandem constructif autour de cette villa des années 70 à Roquefort-les-Pins. Une rénovation complète qui incarne leur concept : Écoute – Adaptation – Détails. Telle est la réalisation présentée dans le magazine Perspective N°31.',
    mission: 'Maîtrise d\'œuvre complète',
    budget: 'Sur demande',
    duration: '18 mois',
    pressArticle: { media: 'Perspective', issue: 'N° 31', pdfUrl: '/presse/perspective-n31.pdf' },
    gallery: [
      '/projects/roquefort/roquefort-1.jpg',
      '/projects/roquefort/roquefort-2.jpg',
      '/projects/roquefort/roquefort-3.jpg',
      '/projects/roquefort/roquefort-4.jpg',
      '/projects/roquefort/roquefort-5.jpg',
    ],
  },
  {
    id: 8,
    slug: 'residence-saint-michel-cannes',
    title: 'Résidence Saint-Michel Valetta — Cannes',
    category: 'Rénovation complète',
    location: 'Cannes',
    surface: 'Résidence',
    year: '2018',
    image: '/presse/n38-photo-3.jpg',
    tags: ['appartement', 'renovation', 'conception'],
    description: 'Dans le prestigieux quartier de la Californie des hauts de Cannes, Christine Thémélidis signe la rénovation complète de la Résidence Saint-Michel Valetta. Sols en marbre Calacatta, couloir d\'entrée monumental avec colonnes en marbre noir, boiseries sur mesure, cuisine ouverte avec vue panoramique sur la Méditerranée, salles de bains luxueuses. Un projet d\'exception publié dans Perspective N°38.',
    mission: 'Rénovation complète & décoration intérieure',
    budget: 'Sur demande',
    duration: '12 mois',
    pressArticle: { media: 'Perspective', issue: 'N° 38', pdfUrl: '/presse/perspective-n38.pdf' },
    gallery: [
      '/presse/n38-photo-1.jpg',
      '/presse/n38-photo-2.jpg',
      '/presse/n38-photo-3.jpg',
      '/presse/n38-photo-4.jpg',
      '/presse/n38-photo-5.jpg',
      '/presse/n38-photo-6.jpg',
      '/presse/n38-photo-7.jpg',
    ],
  },
  {
    id: 9,
    slug: 'residence-gallia-cannes',
    title: 'Appartement traversant — Cannes',
    category: 'Architecture intérieure',
    location: 'Cannes',
    surface: '160 m²',
    year: '2024',
    image: '/projects/gallia/gallia-1.jpg',
    tags: ['appartement', 'renovation', 'conception'],
    description: 'Au cœur de Cannes, Christine Thémélidis signe la rénovation complète d\'un appartement traversant de 160 m² au sein de la Résidence Gallia. Terrasses nord et sud, volumes repensés, finitions haut de gamme. Un projet publié dans le numéro 49 du magazine Perspective.',
    mission: 'Rénovation complète & maîtrise d\'œuvre',
    budget: 'Sur demande',
    duration: 'Sur demande',
    pressArticle: { media: 'Perspective', issue: 'N° 49', pdfUrl: '/presse/perspective-n49.pdf' },
    gallery: [
      '/projects/gallia/gallia-1.jpg',
      '/projects/gallia/gallia-2.jpg',
      '/projects/gallia/gallia-3.jpg',
      '/projects/gallia/gallia-4.jpg',
      '/projects/gallia/gallia-5.jpg',
      '/projects/gallia/gallia-6.jpg',
      '/projects/gallia/gallia-plan.jpg',
    ],
  },
  {
    id: 10,
    slug: 'loft-bruxelles',
    title: 'Loft Bruxelles',
    category: 'Architecture intérieure',
    location: 'Bruxelles',
    surface: 'Loft',
    year: '2022',
    image: '/projects/loft-bruxelles/loft-bruxelles-1.jpg',
    tags: ['loft', 'renovation', 'conception'],
    description: 'Rénovation complète d\'un loft à Bruxelles. Un projet d\'architecture intérieure alliant matériaux nobles et design contemporain : marbre noir, escalier hélicoïdal en métal, terrasse avec garde-corps en verre, et jeux de lumière soignés dans chaque pièce.',
    mission: 'Rénovation complète & décoration intérieure',
    budget: 'Sur demande',
    duration: 'Sur demande',
    gallery: [
      '/projects/loft-bruxelles/loft-bruxelles-1.jpg',
      '/projects/loft-bruxelles/loft-bruxelles-2.jpg',
      '/projects/loft-bruxelles/loft-bruxelles-3.jpg',
      '/projects/loft-bruxelles/loft-bruxelles-4.jpg',
      '/projects/loft-bruxelles/loft-bruxelles-5.jpg',
      '/projects/loft-bruxelles/loft-bruxelles-6.jpg',
      '/projects/loft-bruxelles/loft-bruxelles-7.jpg',
      '/projects/loft-bruxelles/loft-bruxelles-8.jpg',
      '/projects/loft-bruxelles/loft-bruxelles-9.jpg',
    ],
  },
  {
    id: 11,
    slug: 'rez-de-jardin-nice',
    title: 'Un rez de jardin à Nice',
    category: 'Architecture intérieure',
    location: 'Nice',
    surface: 'Appartement',
    year: '2021',
    image: '/projects/rez-jardin-nice/rez-jardin-nice-1.jpg',
    tags: ['appartement', 'renovation', 'jardin'],
    description: 'Rénovation complète d\'un rez de jardin à Nice. Cuisine ouverte avec éclairage indirect, séjour en rotonde ouvert sur un jardin paysagé avec pelouse synthétique et pas japonais. Un projet qui marie confort intérieur et douceur de vivre méditerranéenne.',
    mission: 'Rénovation complète & aménagement extérieur',
    budget: 'Sur demande',
    duration: 'Sur demande',
    gallery: [
      '/projects/rez-jardin-nice/rez-jardin-nice-1.jpg',
      '/projects/rez-jardin-nice/rez-jardin-nice-2.jpg',
      '/projects/rez-jardin-nice/rez-jardin-nice-3.jpg',
      '/projects/rez-jardin-nice/rez-jardin-nice-4.jpg',
    ],
  },
  {
    id: 12,
    slug: 'projection-appartement-cannes-californie',
    title: 'Projection Appartement Cannes Californie',
    category: 'Projection 3D',
    location: 'Cannes',
    surface: 'Appartement',
    year: '2024',
    image: '/projects/cannes-californie/cannes-californie-1.jpg',
    tags: ['appartement', 'projection', 'conception'],
    description: 'Projection 3D d\'un appartement dans le prestigieux quartier de la Californie à Cannes. Conception d\'un salon avec meuble TV sur mesure, chambres avec faux plafonds à éclairage indirect, salle de bains en marbre et mosaïque. Un projet qui illustre la vision d\'AD Concept avant réalisation des travaux.',
    mission: 'Conception & projection 3D',
    budget: 'Sur demande',
    duration: 'Sur demande',
    gallery: [
      '/projects/cannes-californie/cannes-californie-1.jpg',
      '/projects/cannes-californie/cannes-californie-2.jpg',
      '/projects/cannes-californie/cannes-californie-3.jpg',
      '/projects/cannes-californie/cannes-californie-4.jpg',
      '/projects/cannes-californie/cannes-californie-5.jpg',
      '/projects/cannes-californie/cannes-californie-6.jpg',
    ],
  },
  {
    id: 15,
    slug: 'appartement-art-deco',
    title: 'Appartement Art Déco',
    category: 'Rénovation complète',
    location: 'Côte d\'Azur',
    surface: 'Appartement',
    year: '2016',
    image: '/projects/art-deco/art-deco-8.jpg',
    tags: ['appartement', 'renovation', 'conception'],
    description: 'Rénovation complète d\'un appartement de caractère entièrement dédié au style Art Déco. Entrée à coupole lumineuse dorée, porte marquetée sur mesure, salle à manger avec grande table laquée et plafond à caissons, salon avec cheminée en marbre et fauteuils d\'époque. Chaque détail — luminaires, miroirs vénitiens, consoles incrustées — a été sélectionné ou conçu pour servir une cohérence stylistique totale.',
    mission: 'Rénovation complète & décoration',
    budget: 'Sur demande',
    duration: 'Sur demande',
    gallery: [
      '/projects/art-deco/art-deco-8.jpg',
      '/projects/art-deco/art-deco-6.jpg',
      '/projects/art-deco/art-deco-3.jpg',
      '/projects/art-deco/art-deco-1.jpg',
      '/projects/art-deco/art-deco-7.jpg',
      '/projects/art-deco/art-deco-9.jpg',
      '/projects/art-deco/art-deco-4.jpg',
      '/projects/art-deco/art-deco-2.jpg',
      '/projects/art-deco/art-deco-5.jpg',
    ],
  },
  {
    id: 13,
    slug: 'france-3-conception',
    title: 'Conception France 3',
    category: 'Conception & plans',
    location: 'Côte d\'Azur',
    surface: 'Bureaux & studios',
    year: '2013',
    image: '/projects/france3/france3-1.jpg',
    tags: ['conception', 'professionnel'],
    description: 'Mission de conception pour France 3. Élaboration des planches de conception et des plans d\'aménagement des espaces. Un projet professionnel mené avec la rigueur d\'AD Concept.',
    mission: 'Mission de conception',
    budget: 'Sur demande',
    duration: 'Sur demande',
    gallery: [
      '/projects/france3/france3-1.jpg',
      '/projects/france3/france3-2.jpg',
    ],
  },
  {
    id: 2,
    slug: 'villa-pierres-mougins',
    title: 'Villa en pierres — Mougins',
    category: 'Maîtrise d\'œuvre',
    location: 'Mougins',
    surface: '350 m²',
    year: '2014',
    image: '/projects/villa-mougins-1.jpg',
    tags: ['villa', 'renovation'],
    description: 'Rénovation complète d\'une magnifique villa en pierres de taille à Mougins. Préservation du caractère authentique de la bâtisse provençale tout en y apportant le confort contemporain. Création d\'une piscine à débordement, aménagement des extérieurs et restructuration totale des espaces intérieurs.',
    mission: 'Maîtrise d\'œuvre complète + suivi de chantier',
    budget: 'Sur demande',
    duration: '18 mois',
    gallery: [
      '/projects/villa-mougins-1.jpg',
      '/projects/villa-mougins-2.jpg',
      '/projects/villa-mougins-3.jpg',
    ],
  },
]
